server:
  port: 8080
spring:
  datasource:
    first:
      driver-class-name: org.h2.Driver
      jdbcUrl: jdbc:h2:mem:db1
      username: sa
      password:
    second:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:db2
      username: sa
      password:
#  autoconfigure:
#    exclude:
#      - org.mybatis.spring.boot.autoconfigure.MybatisAutoConfiguration
#      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#      - org.springframework.boot.autoconfigure.jdbc.JdbcTemplateAutoConfiguration
#      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration

#management:
#  endpoints:
#    web:
#      exposure:
#        include: beans
